### ISSUE TITLE
где config.ini?

### ISSUE THREAD

**Issue by matrixsx** [Globulopolis/ucoz_converter#1]
Не могу найти конфиг

**Comment by Globulopolis** [comment]
config.ini больше не используется.
Вместо этого в браузере открыть http://сайт/ucoz_converter/index.php настроить и сохранить.

**Comment by matrixsx** [comment]
ошибка
/public_html/ucoz_converter/config.php' (include_path='.:/usr/share/php') in /home/*/web/*.ru/public_html/ucoz_converter/application/framework.php on line 34

**Comment by Globulopolis** [comment]
Подробное описание ошибки приведите и на каком моменте возникает.
И почему у вас путь `/public_html/ucoz_converter/` ведет к `/home//web/.ru/public_html/ucoz_converter/`?

**Comment by matrixsx** [comment]
при переходе  на http://сайт/ucoz_converter/index.php белый экран,  в логи смотрю 
[Mon Mar 09 16:22:27.327768 2020] [php7:error] [pid 25981] [client 45.84.1.24:33938] PHP Fatal error:  require_once(): Failed opening required '/home/1/web/мойсайт.ru/public_html/ucoz_converter/config.php' (include_path='.:/usr/share/php') in /home/1/web/мойсайт.ru/public_html/ucoz_converter/application/framework.php on line 34

**Comment by Globulopolis** [comment]
Обновил репо. Перекачайте заново.

**Comment by Globulopolis** [comment]
Fixed via 7dc7b92
